import { NgModule } from '@angular/core';
import { CommonModule } from "@angular/common";
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { InputModule, ButtonModule, SliderModule, SearchModule, TableModule, ProgressIndicatorModule, ToggleModule, FileUploaderModule, 
     PaginationModule, DialogModule, ModalModule, RadioModule, AccordionModule ,NumberModule,DropdownModule,SelectModule,TagModule, CheckboxModule, 
     NotificationModule, PlaceholderModule, LoadingModule, BreadcrumbModule
    } from 'carbon-components-angular';
// import { CheckmarkFilledModule } from '@carbon/icons-angular/checkmark--filled';

// import { ViewModule } from '@carbon/icons-angular/view';
// import { ViewOffModule } from '@carbon/icons-angular/view--off';
import { CheckmarkFilledModule, InformationModule, ViewModule, ViewOffModule, ChevronDownModule, ChevronUpModule,ChevronRightModule,
    ArrowLeftModule, ArrowRightModule, HomeModule, SettingsModule, UserFilledModule, PlayOutlineModule, ChevronLeftModule,
    DataStructuredModule, Data_1Module, CheckmarkModule, CloseModule, RadioButtonModule, CollaborateModule, UploadModule,
    DeleteModule, UnlockedModule, DownloadModule, FolderModule, FolderAddModule, AddModule, SubtractAltModule,DocumentExportModule,
    RenewModule, TerminalModule, EditModule, UndoModule, YAxisModule, CaretUpModule, CaretDownModule, SettingsAdjustModule, 
    VisualRecognitionModule, WarningFilledModule, WarningModule, DocumentModule
} from '@carbon/icons-angular';


@NgModule({
    declarations: [
    ],
    imports: [
        CommonModule,
        FormsModule,
        ReactiveFormsModule,
        ButtonModule,
        SearchModule,
        ProgressIndicatorModule,
        SliderModule,
        TableModule,
        FileUploaderModule,
        PaginationModule,
        DialogModule,
        RadioModule,
        DropdownModule,
        ToggleModule,
        ModalModule,
        NotificationModule,
        SelectModule,
        // RadioButtonGroupModule,
        // DataTableModule,
        CheckboxModule,
        // RadioButtonModule,
        CheckboxModule,
        // TooltipModule,
        FormsModule,
        ReactiveFormsModule,
        CommonModule,
        InputModule,
        CheckmarkFilledModule,
        AccordionModule,
        ViewModule,
        ViewOffModule,
        ChevronUpModule,
        ChevronLeftModule,
        ChevronRightModule,
        ChevronDownModule,
        PlaceholderModule,
        InformationModule,
        ArrowLeftModule, 
        ArrowRightModule,
        HomeModule,
        SettingsModule,
        UserFilledModule,
        DataStructuredModule,
        Data_1Module,
        LoadingModule,
        CheckmarkModule,
        RadioButtonModule,
        CollaborateModule,
        PlayOutlineModule,
        CloseModule,
        BreadcrumbModule,
        UploadModule,
        DeleteModule, UnlockedModule, DownloadModule, FolderModule, FolderAddModule, AddModule, SubtractAltModule,DocumentExportModule,
        RenewModule, TerminalModule, EditModule, UndoModule, YAxisModule, CaretUpModule, CaretDownModule, SettingsAdjustModule, 
        VisualRecognitionModule, WarningFilledModule, WarningModule, DocumentModule
    ],
    exports: [
        SliderModule,
        TableModule,
        FileUploaderModule,
        PaginationModule,
        DialogModule,
        RadioModule,
        DropdownModule,
        ButtonModule,
        SearchModule,
        ProgressIndicatorModule,
        ToggleModule,
        ModalModule,
        NotificationModule,
        SelectModule,
        // RadioButtonGroupModule,
        // DataTableModule,
        CheckboxModule,
        // RadioButtonModule,
        // TooltipModule,
        FormsModule,
        CommonModule,
        InputModule,
        CheckmarkFilledModule,
        AccordionModule,
        PlaceholderModule,
        ViewModule,
        ViewOffModule,
        ChevronDownModule,
        ChevronUpModule,
        ChevronLeftModule,
        ChevronRightModule,
        InformationModule,
        ArrowLeftModule, 
        ArrowRightModule,
        HomeModule,
        SettingsModule,
        UserFilledModule,
        DataStructuredModule,
        Data_1Module,
        LoadingModule,
        CheckmarkModule,
        RadioButtonModule,
        CollaborateModule,
        PlayOutlineModule,
        CloseModule,
        BreadcrumbModule,
        UploadModule,
        DeleteModule, UnlockedModule, DownloadModule, FolderModule, FolderAddModule, AddModule, SubtractAltModule,DocumentExportModule,
        RenewModule, TerminalModule, EditModule, UndoModule, YAxisModule, CaretUpModule, CaretDownModule, SettingsAdjustModule, 
        VisualRecognitionModule, WarningFilledModule, WarningModule, DocumentModule
    ]
})
export class ShareModule {}
